const qnaCategory = [
  { langId: 1, langName: "JavaScript" },
  { langId: 2, langName: "Nodejs" },
  { langId: 3, langName: "React" },
  { langId: 4, langName: "Vue" },
  { langId: 5, langName: "Kotline" },
  { langId: 6, langName: "Java" },
  { langId: 7, langName: "Python" },
  { langId: 8, langName: "C" },
  { langId: 9, langName: "C++" },
  { langId: 10, langName: "C#" },
  { langId: 11, langName: "CSS" },
  { langId: 12, langName: "PHP" },
];

const interestCategory = [
  { interestId: 1, interestName: "Javascript" },
  { interestId: 2, interestName: "Java" },
  { interestId: 3, interestName: "Python" },
  { interestId: 4, interestName: "HTML" },
  { interestId: 5, interestName: "CSS" },
  { interestId: 6, interestName: "C++" },
  { interestId: 7, interestName: "C#" },
  { interestId: 8, interestName: "PHP" },
  { interestId: 9, interestName: "Kotlin" },
  { interestId: 10, interestName: "Swift" },
  { interestId: 11, interestName: "Vue" },
  { interestId: 12, interestName: "React" },
  { interestId: 13, interestName: "Angular" },
  { interestId: 14, interestName: "Node" },
  { interestId: 15, interestName: "Spring" },
  { interestId: 16, interestName: "SQL" },
  { interestId: 17, interestName: "Assembly language" },
  { interestId: 18, interestName: "TypeScript" },
  { interestId: 19, interestName: "Objective-C" },
  { interestId: 20, interestName: "Go" },
];

const jobs = [
  "웹개발자",
  "서버개발자",
  "프론트엔드 개발자",
  "소프트웨어 엔지니어",
  "자바 개발자",
  "안드로이드 개발자",
  "iOS 개발자",
  "Node.js 개발자",
  "C,C++ 개발자",
  "데이터 엔지니어",
  "파이썬 개발자",
  "DevOps/시스템관리자",
  "머신러닝 엔지니어",
  "데이터 사이언티스트",
  "빅데이터 엔지니어",
  "기술지원",
  "개발 매니저",
  "QA 테스트엔지니어",
  "보안 엔지니어",
  "프로덕트매니저",
  "PHP 개발자",
  "블록체인 플랫폼 엔지니어",
  "임베디드 개발자",
  "웹 퍼블리셔",
  " 하드웨어 엔지니어",
];

const career = [
  "1년 이하",
  "1년 이상",
  "2년 이상",
  "3년 이상",
  "4년 이상",
  "5년 이상",
  "10년 이상",
  "15년 이상",
  "20년 이상",
];

const categories = {
  qnaCategory,
  interestCategory,
  jobs,
  career,
};

export default categories;
